[package]
name = "sf_fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
sf-api = { version = "0.3.1", features = ["session", "sso"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
